### ISSUE TITLE
Does not fetch all paths from the cache

### ISSUE THREAD

**Issue by FRidh** [DeterminateSystems/magic-nix-cache-action#18]
The action successfully pushes paths produced to a cache, but I noticed that not all paths that it should fetch are fetched. It fetches from cache.nixos.org, and some paths from the GH cache at 127.0.0.1, but then many other packages it should fetch it starts building from source again.
```

name: "CI using nix"

on:
    push:
      branches:
        - develop
        - main

    pull_request:
      branches:
        - develop
        - main

jobs:
    check:
        runs-on: ubuntu-22.04
        steps:
        - uses: actions/checkout@v3
        - uses: DeterminateSystems/nix-installer-action@main
          with:
            nix-installer-tag: v0.10.0
            extra-conf: |-
              experimental-features = nix-command flakes impure-derivations ca-derivations
        - uses: DeterminateSystems/magic-nix-cache-action@main
        - run: nix flake check --print-build-logs
```

I've checked the logs and it is not due to rate limiting. If I check the `Caches` page it does say items were recently used. There are about 86 pages of caches. There is no warning that the space limit is (almost) reached.
