### ISSUE TITLE
Is the cache not saved when there is a build failure?

### ISSUE THREAD

**Issue by FRidh** [DeterminateSystems/magic-nix-cache-action#9]
When a failure occurs during a build, do the other store paths still get cached or not? I have the impression they're not. The runs I am doing require quite some building so it takes some time to get better insights.

```yml
name: "CI using nix"

on:
    push:
      branches:
        - develop
        - main

    pull_request:
      branches:
        - develop
        - main

jobs:
    check:
        runs-on: ubuntu-22.04
        steps:
        - uses: actions/checkout@v3
        - uses: DeterminateSystems/nix-installer-action@main
          with:
            extra-conf: |
              extra-experimental-features = nix-command flakes impure-derivations ca-derivations
        - uses: DeterminateSystems/magic-nix-cache-action@main
        - run: nix flake check
```
